import React, { useState, useEffect } from 'react';
import { Lightbulb, Sparkles, Star, Rocket, TrendingUp, X, Target, Calendar, Award, Briefcase, ExternalLink, Zap, Clock, BarChart3, ChevronRight } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { GlassCard } from '../components/GlassCard';
import { careerAPI } from '../services/api';

export default function CareerMatch() {
  const [selectedCareer, setSelectedCareer] = useState(null);
  const [recommendations, setRecommendations] = useState([]);
  const [simulation, setSimulation] = useState(null);
  const [loading, setLoading] = useState(true);
  const [simulating, setSimulating] = useState(false);
  const [error, setError] = useState('');
  const [allCareers, setAllCareers] = useState([]);

  const loadingMessages = [
    'Analyzing your unique skill DNA...',
    'Cross-referencing 10,000+ career paths...',
    'Consulting our AI career oracle...',
    'Calculating your perfect career fit...',
    'Mapping your strengths to opportunities...',
    'Scanning the job market universe...',
    'Running neural match algorithms...',
    'Almost there... your future is loading!'
  ];
  const [loadingMsgIdx, setLoadingMsgIdx] = useState(0);

  useEffect(() => {
    if (!loading) return;
    const interval = setInterval(() => setLoadingMsgIdx(i => (i + 1) % loadingMessages.length), 2500);
    return () => clearInterval(interval);
  }, [loading]);

  const itemAnim = { hidden: { opacity: 0, y: 20 }, show: { opacity: 1, y: 0, transition: { duration: 0.5 } } };

  const colorPalette = ['#8c5bf5', '#eab308', '#f43f5e', '#06b6d4', '#10b981'];
  const riskLabels = (score) => {
    if (score >= 80) return { label: 'Low Risk', color: 'emerald' };
    if (score >= 60) return { label: 'Medium Risk', color: 'yellow' };
    return { label: 'High Risk', color: 'rose' };
  };

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        const [recRes, careersRes] = await Promise.all([
          careerAPI.getRecommendations(),
          careerAPI.getCareers()
        ]);
        
        setAllCareers(careersRes.data || []);
        
        const recs = recRes.data?.recommendations || recRes.data || [];
        setRecommendations(recs.slice(0, 5));
      } catch (err) {
        console.error('Failed to fetch recommendations:', err);
        setError('Failed to load career recommendations.');
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  const handleSimulate = async (rec) => {
    const career = allCareers.find(c => c.name === rec.careerName);
    if (!career) return;
    
    setSimulating(true);
    try {
      const res = await careerAPI.simulateCareer({ careerId: career._id });
      setSimulation(res.data);
      setSelectedCareer({ 
        title: rec.careerName, 
        match: `${rec.fitScore}%`, 
        color: colorPalette[recommendations.indexOf(rec) % colorPalette.length],
        data: res.data 
      });
    } catch (err) {
      console.error('Simulation failed:', err);
    } finally {
      setSimulating(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center w-full h-full min-h-[60vh]">
        <div className="flex flex-col items-center gap-4">
          <div className="relative">
            <div className="w-16 h-16 border-4 border-[#8c5bf5]/20 border-t-[#8c5bf5] rounded-full animate-spin"></div>
            <Sparkles size={20} className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-[#8c5bf5] animate-pulse" />
          </div>
          <motion.p
            key={loadingMsgIdx}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="text-slate-400 text-sm font-medium text-center max-w-xs"
          >
            {loadingMessages[loadingMsgIdx]}
          </motion.p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-6 pb-4 max-w-7xl mx-auto w-full relative">
      
      {/* AI Insight Box */}
      <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.5 }}>
        <GlassCard className="p-6 flex items-start gap-4 border-l-4 border-l-[#8c5bf5] relative overflow-hidden mt-2">
          <div className="absolute top-0 right-0 p-8 opacity-10 pointer-events-none">
            <Lightbulb size={100} />
          </div>
          <div className="bg-[#8c5bf5]/20 p-3 rounded-full text-[#8c5bf5]">
            <Sparkles size={24} />
          </div>
          <div className="space-y-1 relative z-10">
            <h3 className="font-bold text-lg text-white">AI Recommendation Engine</h3>
            <p className="text-slate-300 leading-relaxed text-sm">
              Career matches generated by AI based on your skills, quiz performance, and career DNA profile.
            </p>
          </div>
        </GlassCard>
      </motion.div>

      {/* Career Matches */}
      <section className="space-y-6 mt-4">
        <h3 className="text-xl font-bold flex items-center gap-2 text-white">
          <Star size={20} className="text-[#8c5bf5] fill-[#8c5bf5]" /> Top Career Matches
        </h3>
        
        {error && (
          <GlassCard className="p-4 border border-red-500/30 bg-red-500/5">
            <p className="text-red-400 text-sm">{error}</p>
          </GlassCard>
        )}

        {recommendations.length === 0 && !error && (
          <GlassCard className="p-8 text-center">
            <p className="text-slate-400">No recommendations yet. Complete quizzes to improve matches.</p>
          </GlassCard>
        )}
        
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {recommendations.map((rec, index) => {
            const color = colorPalette[index % colorPalette.length];
            const risk = riskLabels(rec.fitScore);
            const career = allCareers.find(c => c.name === rec.careerName);
            const salary = career?.averageSalaryRange || {};
            const salaryStr = salary.min && salary.max 
              ? `$${(salary.min / 1000).toFixed(0)}k - $${(salary.max / 1000).toFixed(0)}k` 
              : 'N/A';

            return (
              <motion.div key={index} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 * index, duration: 0.5 }}>
                <GlassCard className="p-6 relative group flex flex-col h-full" style={{ borderTop: `2px solid ${color}50` }}>
                  <div className="flex justify-between items-start mb-6">
                    <div className="w-14 h-14 rounded-2xl flex items-center justify-center text-white shadow-lg" style={{ background: `${color}30`, color }}>
                      <Target size={28} />
                    </div>
                    <div className="text-right">
                      <div className="text-3xl font-black" style={{ color }}>{rec.fitScore}%</div>
                      <div className="text-[10px] font-bold uppercase tracking-widest text-slate-500">Fit Score</div>
                    </div>
                  </div>
                  <h4 className="text-xl font-bold mb-1 text-white">{rec.careerName}</h4>
                  <div className="flex items-center gap-2 mb-4">
                    <span className={`px-3 py-1 rounded-full bg-${risk.color}-500/10 text-${risk.color}-500 text-[10px] font-bold uppercase`}>{risk.label}</span>
                    <span className="text-slate-500 text-xs font-medium">{salaryStr}</span>
                  </div>
                  <p className="text-slate-400 text-sm mb-2 leading-relaxed">{rec.strengthReason}</p>
                  {rec.riskReason && <p className="text-slate-500 text-xs mb-6 italic">{rec.riskReason}</p>}
                  
                  <button 
                    onClick={() => handleSimulate(rec)}
                    disabled={simulating}
                    className="mt-auto w-full py-3 rounded-full text-white text-sm font-bold flex items-center justify-center gap-2 transition-all hover:scale-[1.02]"
                    style={{ background: index === 0 ? `linear-gradient(to right, ${color}, #4f46e5)` : 'rgba(30,27,46,1)', border: index === 0 ? 'none' : '1px solid rgba(255,255,255,0.05)' }}
                  >
                    {simulating ? 'Simulating...' : 'Simulate Future'} <Rocket size={16} />
                  </button>
                </GlassCard>
              </motion.div>
            );
          })}
        </div>
      </section>

      {/* --- CAREER SIMULATION MODAL --- */}
      <AnimatePresence>
        {selectedCareer && simulation && (() => {
          const prob = simulation.probability ?? 0;
          const circumference = 2 * Math.PI * 54;
          const strokeDash = (prob / 100) * circumference;
          const probColor = prob >= 70 ? '#10b981' : prob >= 40 ? '#eab308' : '#f43f5e';
          const diffLabel = simulation.difficultyScore >= 70 ? 'Hard' : simulation.difficultyScore >= 40 ? 'Medium' : 'Easy';
          const demandLabel = simulation.marketDemandScore >= 70 ? 'High' : simulation.marketDemandScore >= 40 ? 'Medium' : 'Low';
          return (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-[#0a0b1e]/85 backdrop-blur-lg overflow-y-auto">
            <motion.div
              initial={{ opacity: 0, scale: 0.9, y: 30 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.9, y: 30 }}
              transition={{ type: 'spring', damping: 25, stiffness: 300 }}
              className="w-full max-w-3xl my-8"
            >
              <div className="relative rounded-3xl overflow-hidden border border-white/10 bg-[#12101f]/95 backdrop-blur-xl shadow-[0_0_60px_rgba(140,91,245,0.15)]">
                {/* Glowing top bar */}
                <div className="h-1.5 w-full" style={{ background: `linear-gradient(to right, ${selectedCareer.color}, #4f46e5, ${selectedCareer.color})` }} />
                
                {/* Background glow */}
                <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[60%] h-40 rounded-full blur-[100px] opacity-20" style={{ backgroundColor: selectedCareer.color }} />
                
                <div className="p-8 relative z-10">
                  {/* Header */}
                  <div className="flex justify-between items-start mb-8">
                    <div>
                      <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest mb-2" style={{ color: selectedCareer.color }}>
                        <Zap size={14} /> Career Simulation Engine
                      </div>
                      <h2 className="text-3xl font-black text-white">{selectedCareer.title}</h2>
                      <p className="text-slate-400 text-sm mt-1">AI-powered path simulation based on your Career DNA</p>
                    </div>
                    <button 
                      onClick={() => { setSelectedCareer(null); setSimulation(null); }}
                      className="text-slate-400 hover:text-white bg-white/5 hover:bg-white/10 p-2.5 rounded-full transition-all hover:rotate-90 duration-300"
                    >
                      <X size={18} />
                    </button>
                  </div>

                  {/* Probability Ring + Key Stats */}
                  <div className="flex flex-col md:flex-row items-center gap-8 mb-8">
                    {/* Probability Ring */}
                    <div className="relative flex-shrink-0">
                      <svg width="140" height="140" className="transform -rotate-90">
                        <circle cx="70" cy="70" r="54" stroke="rgba(255,255,255,0.05)" strokeWidth="10" fill="none" />
                        <motion.circle
                          cx="70" cy="70" r="54"
                          stroke={probColor}
                          strokeWidth="10"
                          fill="none"
                          strokeLinecap="round"
                          strokeDasharray={circumference}
                          initial={{ strokeDashoffset: circumference }}
                          animate={{ strokeDashoffset: circumference - strokeDash }}
                          transition={{ duration: 1.5, ease: 'easeOut' }}
                          style={{ filter: `drop-shadow(0 0 8px ${probColor}60)` }}
                        />
                      </svg>
                      <div className="absolute inset-0 flex flex-col items-center justify-center">
                        <span className="text-3xl font-black text-white">{prob}%</span>
                        <span className="text-[9px] font-bold uppercase tracking-widest text-slate-400">Success</span>
                      </div>
                    </div>

                    {/* Stats Grid */}
                    <div className="grid grid-cols-2 gap-3 flex-1 w-full">
                      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}
                        className="p-4 bg-gradient-to-br from-white/[0.06] to-transparent border border-white/10 rounded-2xl">
                        <div className="flex items-center gap-2 mb-2">
                          <Clock size={14} style={{ color: selectedCareer.color }} />
                          <span className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Est. Timeline</span>
                        </div>
                        <p className="text-2xl font-black text-white">{simulation.totalDays ?? 'N/A'} <span className="text-sm font-medium text-slate-400">days</span></p>
                      </motion.div>
                      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}
                        className="p-4 bg-gradient-to-br from-white/[0.06] to-transparent border border-white/10 rounded-2xl">
                        <div className="flex items-center gap-2 mb-2">
                          <Award size={14} style={{ color: selectedCareer.color }} />
                          <span className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Study Hours</span>
                        </div>
                        <p className="text-2xl font-black text-white">{simulation.totalHours ?? 'N/A'}<span className="text-sm font-medium text-slate-400">h</span></p>
                      </motion.div>
                      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }}
                        className="p-4 bg-gradient-to-br from-emerald-500/[0.06] to-transparent border border-emerald-500/10 rounded-2xl">
                        <div className="flex items-center gap-2 mb-2">
                          <Briefcase size={14} className="text-emerald-400" />
                          <span className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Job Openings</span>
                        </div>
                        <p className="text-2xl font-black text-emerald-400">{(simulation.totalJobs ?? 0).toLocaleString()}</p>
                      </motion.div>
                      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.5 }}
                        className="p-4 bg-gradient-to-br from-white/[0.06] to-transparent border border-white/10 rounded-2xl">
                        <div className="flex items-center gap-2 mb-2">
                          <BarChart3 size={14} style={{ color: selectedCareer.color }} />
                          <span className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Difficulty</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <p className="text-2xl font-black text-white">{simulation.difficultyScore ?? 'N/A'}</p>
                          <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${simulation.difficultyScore >= 70 ? 'bg-red-500/10 text-red-400' : simulation.difficultyScore >= 40 ? 'bg-yellow-500/10 text-yellow-400' : 'bg-emerald-500/10 text-emerald-400'}`}>{diffLabel}</span>
                        </div>
                      </motion.div>
                    </div>
                  </div>

                  {/* Market Demand + Quick Insights */}
                  <div className="flex items-center gap-3 mb-6 flex-wrap">
                    <span className={`text-[10px] font-bold px-3 py-1.5 rounded-full border ${simulation.marketDemandScore >= 70 ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-400' : simulation.marketDemandScore >= 40 ? 'bg-yellow-500/10 border-yellow-500/20 text-yellow-400' : 'bg-red-500/10 border-red-500/20 text-red-400'}`}>
                      {demandLabel} Market Demand
                    </span>
                    <span className="text-[10px] font-bold px-3 py-1.5 rounded-full border border-white/10 bg-white/5 text-slate-300">
                      {simulation.gaps?.length || 0} Skills to Close
                    </span>
                    {simulation.totalDays && simulation.totalDays <= 90 && (
                      <span className="text-[10px] font-bold px-3 py-1.5 rounded-full border border-[#8c5bf5]/20 bg-[#8c5bf5]/10 text-[#8c5bf5]">
                        Fast Track Available
                      </span>
                    )}
                  </div>

                  {/* Skill Gap Bars */}
                  {simulation.gaps && simulation.gaps.length > 0 && (
                    <div className="mb-6">
                      <h4 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2 mb-4">
                        <Target size={14} style={{ color: selectedCareer.color }} /> Skill Gap Analysis
                      </h4>
                      <div className="space-y-3">
                        {simulation.gaps.map((gap, i) => {
                          const pct = gap.requiredLevel ? Math.min(100, ((gap.userLevel || 0) / gap.requiredLevel) * 100) : 0;
                          const gapColor = pct >= 80 ? '#10b981' : pct >= 50 ? '#eab308' : '#f43f5e';
                          return (
                            <motion.div key={i} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.1 * i }}
                              className="p-3 bg-white/[0.03] border border-white/5 rounded-xl">
                              <div className="flex justify-between items-center mb-2">
                                <span className="text-sm text-white font-semibold">{gap.skill}</span>
                                <div className="flex items-center gap-3 text-xs">
                                  <span className="text-slate-400">{Math.round(gap.userLevel || 0)} <span className="text-slate-600">/ {gap.requiredLevel}</span></span>
                                  <span className="font-bold" style={{ color: gapColor }}>{Math.round(pct)}%</span>
                                </div>
                              </div>
                              <div className="h-1.5 bg-white/5 rounded-full overflow-hidden">
                                <motion.div
                                  className="h-full rounded-full"
                                  style={{ backgroundColor: gapColor }}
                                  initial={{ width: 0 }}
                                  animate={{ width: `${pct}%` }}
                                  transition={{ duration: 0.8, delay: 0.1 * i }}
                                />
                              </div>
                              {gap.estimatedHours > 0 && (
                                <p className="text-[10px] text-slate-500 mt-1">{gap.estimatedHours}h estimated to close</p>
                              )}
                            </motion.div>
                          );
                        })}
                      </div>
                    </div>
                  )}

                  {/* Sample Job Listings */}
                  {simulation.sampleJobs && simulation.sampleJobs.length > 0 && (
                    <div className="mb-6">
                      <h4 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2 mb-4">
                        <Briefcase size={14} className="text-emerald-400" /> Live Job Openings
                      </h4>
                      <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                        {simulation.sampleJobs.slice(0, 3).map((job, i) => (
                          <motion.div key={i} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 * i }}
                            className="p-4 bg-white/[0.03] border border-white/5 rounded-xl hover:border-emerald-500/20 transition-all group">
                            <p className="text-sm text-white font-semibold truncate mb-1">{job.title}</p>
                            <p className="text-[10px] text-slate-400 truncate mb-3">{job.company}</p>
                            <div className="flex items-center justify-between">
                              <span className="text-[10px] text-slate-500 truncate">{job.location}</span>
                              <div className="flex items-center gap-2 shrink-0">
                                {job.salary && <span className="text-[10px] text-emerald-400 font-bold">{job.salary}</span>}
                                {job.applyLink && (
                                  <a href={job.applyLink} target="_blank" rel="noopener noreferrer" className="text-[#8c5bf5] hover:text-white transition-colors">
                                    <ExternalLink size={12} />
                                  </a>
                                )}
                              </div>
                            </div>
                          </motion.div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Action Buttons */}
                  <div className="flex gap-3">
                    <button 
                      onClick={() => { setSelectedCareer(null); setSimulation(null); }}
                      className="flex-1 py-4 text-white font-bold rounded-2xl shadow-lg transition-all hover:brightness-110 flex items-center justify-center gap-2"
                      style={{ background: `linear-gradient(135deg, ${selectedCareer.color}, #4f46e5)` }}
                    >
                      Close Simulation
                    </button>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
          );
        })()}
      </AnimatePresence>

    </div>
  );
}